export enum UserRole {
  ADMIN = 'ADMIN',
  CONTENT = 'CONTENT',
  GAMES_ADMIN = 'GAMES_ADMIN',
  SPORT_MANAGER = 'SPORT_MANAGER',
  VENUE_OPERATOR = 'VENUE_OPERATOR',
  SCOREKEEPER = 'SCOREKEEPER',
  RESULT_APPROVER = 'RESULT_APPROVER',
  READ_ONLY = 'READ_ONLY',
}
