export const INTEGRATION_FIELDS = [
  { name: 'SMTP_HOST', group: 'SMTP', label: 'Máy chủ SMTP' },
  { name: 'SMTP_PORT', group: 'SMTP', label: 'Cổng SMTP', kind: 'port' },
  { name: 'SMTP_SECURE', group: 'SMTP', label: 'TLS (true / false)', kind: 'boolean' },
  { name: 'SMTP_USER', group: 'SMTP', label: 'Tên đăng nhập' },
  { name: 'SMTP_PASSWORD', group: 'SMTP', label: 'Mật khẩu', secret: true },
  { name: 'SMTP_FROM', group: 'SMTP', label: 'Địa chỉ gửi' },
  { name: 'FPT_AI_API_KEY', group: 'FPT.AI', label: 'API key', secret: true },
  { name: 'FPT_AI_ID_ENDPOINT', group: 'FPT.AI', label: 'URL OCR CCCD', kind: 'url' },
  { name: 'FPT_AI_PASSPORT_ENDPOINT', group: 'FPT.AI', label: 'URL OCR hộ chiếu', kind: 'url' },
  { name: 'MOMO_PARTNER_CODE', group: 'MoMo', label: 'Partner Code' },
  { name: 'MOMO_ACCESS_KEY', group: 'MoMo', label: 'Access Key', secret: true },
  { name: 'MOMO_SECRET_KEY', group: 'MoMo', label: 'Secret Key', secret: true },
  { name: 'MOMO_API_URL', group: 'MoMo', label: 'URL API', kind: 'url' },
  { name: 'MOMO_PARTNER_NAME', group: 'MoMo', label: 'Tên đối tác' },
  { name: 'MOMO_STORE_ID', group: 'MoMo', label: 'Store ID' },
  { name: 'VNPAY_TMN_CODE', group: 'VNPAY', label: 'TMN Code' },
  { name: 'VNPAY_HASH_SECRET', group: 'VNPAY', label: 'Hash Secret', secret: true },
  { name: 'VNPAY_PAYMENT_URL', group: 'VNPAY', label: 'URL thanh toán', kind: 'url' },
] as const;
