ALTER TABLE "Event"
ADD COLUMN "ticketThemePreset" TEXT NOT NULL DEFAULT 'OCEAN',
ADD COLUMN "ticketLayout" TEXT NOT NULL DEFAULT 'CLASSIC',
ADD COLUMN "ticketPrimaryColor" TEXT NOT NULL DEFAULT '#0284C7',
ADD COLUMN "ticketSecondaryColor" TEXT NOT NULL DEFAULT '#075985',
ADD COLUMN "ticketAccentColor" TEXT NOT NULL DEFAULT '#059669';
