ALTER TYPE "SportDataAccountType" ADD VALUE IF NOT EXISTS 'GENERAL';
ALTER TYPE "SportDataAccountType" ADD VALUE IF NOT EXISTS 'REFEREE';
ALTER TYPE "SportDataAccountType" ADD VALUE IF NOT EXISTS 'TEAM_LEADER';
ALTER TYPE "SportDataAccountType" ADD VALUE IF NOT EXISTS 'COACH';
ALTER TYPE "SportDataAccountType" ADD VALUE IF NOT EXISTS 'MEDICAL';
